"""Add marital status and family fields

Revision ID: 2540cb3d012e
Revises: 
Create Date: 2025-09-07 22:50:42.110520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2540cb3d012e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marital_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('father_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mother_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('spouse_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('have_children', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('children_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.drop_column('children_data')
        batch_op.drop_column('have_children')
        batch_op.drop_column('spouse_name')
        batch_op.drop_column('mother_name')
        batch_op.drop_column('father_name')
        batch_op.drop_column('marital_status')

    # ### end Alembic commands ###
